version: "3.8"

services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: rentachair
    ports:
      - "5433:5432"  # Changed from 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data

  medusa:
    build:
      context: ./apps/commerce
      dockerfile: Dockerfile
    environment:
      DATABASE_URL: postgres://${DB_USER}:${DB_PASSWORD}@postgres:5432/rentachair
      NODE_ENV: development
      PORT: 9000
      DATABASE_TYPE: postgres
    ports:
      - "9000:9000"
    depends_on:
      - postgres
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:9000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  payload:
    build:
      context: ./apps/cms
      dockerfile: Dockerfile
    environment:
      DATABASE_URI: postgres://${DB_USER}:${DB_PASSWORD}@postgres:5432/rentachair
      PAYLOAD_SECRET: your-secret-key
      PORT: 3001
    ports:
      - "3001:3001"
    depends_on:
      - postgres
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3001/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  postgres_data: