version: "3.8"

services:
  web:
    build: 
      context: ./apps/web
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_MEDUSA_BACKEND_URL=http://commerce:9000
      - NEXT_PUBLIC_SITE_URL=http://localhost:3000

  commerce:
    build:
      context: ./apps/commerce
      dockerfile: Dockerfile
    ports:
      - "9000:9000"
    environment:
      - DATABASE_URL=postgres://postgres:postgres@postgres:5432/rent-a-chair
      - REDIS_URL=redis://redis:6379

  cms:
    build:
      context: ./apps/cms
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/rent-a-chair
      - PAYLOAD_PUBLIC_SERVER_URL=http://localhost:3001

  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: rent-a-chair
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

volumes:
  postgres_data:
  mongodb_data: